version: '3'

services:

  key:
    container_name: ${PROJECT_NAME}-key
    build: ./build/key
    working_dir: /tmp
    networks:
      - app_network
    volumes:
      - keys-data:/tmp 
     

  # Servidor web NGINX
  web:
    container_name: ${PROJECT_NAME}-web
    image: nginx:alpine
    ports:
      - ${PROJECT_PORT}:80
    networks:
      - app_network
    volumes:      
      - project-data:/src/public
      - ./conf/nginx:/etc/nginx/conf.d
     
    depends_on:
      - php

  # PHP-FPM
  php:
    container_name: ${PROJECT_NAME}-php
    build: ./build/php
    networks:
      - app_network
    expose:
      - 9000
    volumes:
      - keys-data:/config/.ssh 
      - project-data:/src/public
      - ./conf/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./conf/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./conf/php/memory.ini:/usr/local/etc/php/conf.d/memory.ini
      - ./conf/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./conf/php/apcu.ini:/usr/local/etc/php/conf.d/apcu.ini
     

  # Banco de dados Mysql
  mysql:
    container_name: ${PROJECT_NAME}-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app_network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1    
    networks:
      - app_network


  # Messageria NATS
  nats:
    container_name: ${PROJECT_NAME}-nats
    image: nats:latest    
    restart: unless-stopped
    ports:
        - ${NATS_PORT}:4222
    networks:
      - app_network  

  # Banco de dados de memoria Redis
  redis:
    container_name: ${PROJECT_NAME}-redis
    image: redis:latest
    command: redis-server --save 60 1 --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81 --loglevel 
    volumes:
      - redis-data:/data
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - app_network  

  # VSCode (code-server)
  vscode:
    build: ./build/code
    container_name: ${PROJECT_NAME}-vscode
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - DEFAULT_WORKSPACE=/config/src
      - PASSWORD=${VSCODE_USER_PASS}                   #optional
      # - HASHED_PASSWORD=${VSCODE_USER_HASH_PASS}     #optional
      # - SUDO_PASSWORD=${VSCODE_ROOT_PASS}            #optional
      # - SUDO_PASSWORD_HASH=${VSCODE_USER_HASH_PASS}  #optional
      # - PROXY_DOMAIN=${VSCODE_PROXY_DOMAIN}          #optional
    volumes:
      - ../vscode:/config
      - project-data:/config/src
      - keys-data:/config/.ssh  
    depends_on:
      - php
      - web
    ports:
      - ${VSCODE_PORT}:8443
    networks:
      - app_network

networks:
  app_network:

volumes:
    keys-data:
      external: false
    project-data:
      external: false
    mysql-data:
      external: false
    redis-data:
      external: false
        
        
        
        
